sudo: required
services:
  - docker
before_install:
  -  openssl aes-256-cbc -K $encrypted_ad22c6a9d628_key -iv $encrypted_ad22c6a9d628_iv -in multi-k8s-369320-2c540962f865.json.enc -out multi-k8s-369320-2c540962f865.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
