sudo: required
services:
  - docker

before_install:
  - docker build -t sooyouz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sooyouz/react-test npm test
after_success:
  - docker build -t sooyouz/multi-client -f ./client/Dockerfile ./client
  - docker build -t sooyouz/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t sooyouz/multi-server -f ./nginx/Dockerfile ./server
  - docker build -t sooyouz/multi-worker -f ./nginx/Dockerfile ./worker
language: generic 