sudo: required
services:
  - docker

before_install:
  - docker build -t sooyouz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sooyouz/react-test npm test
after_success:
  - docker build -t sooyouz/multi-client -f ./client/Dockerfile ./client
  - docker build -t sooyouz/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t sooyouz/multi-server -f ./server/Dockerfile ./server
  - docker build -t sooyouz/multi-worker -f ./worker/Dockerfile ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sooyouz/multi-client
  - docker push sooyouz/multi-nginx
  - docker push sooyouz/multi-server
  - docker push sooyouz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ue-west-3'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-188497965282'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

language: generic 